### ISSUE TITLE
.equals vs == for strings again

### ISSUE THREAD

**Issue by stretchycritter** [DemonicBroccoli/MyGlitchRiddenGame#1]
You problem seems to be that your using the == notation again where you can't. On line 59 in the MainGame file you use == for each of the comparisons for "fire". Instead you should use the following.

```
if(userInput.equals("fire") || userInput.equals("Fire") || userInput.equals("FIRE"))
```

Also, you can use the toLowerCase to reduce your checks from 3 to 1.

```
if(userInput.toLowerCase().equals("fire"))
{
    //Do stuff here
}
```

This turns the users input into lowercase then compares it to a string of your choosing. Useful when you know what the user needs to enter, but not the formatting they enter it in.

I believe this will solve your problem since I was able to get the game to repeat again once I set this. When it was the old == notation, it would just restart the game every time I tried to enter "fire". If this didn't solve the problem and I miss interpreted what you were saying let me know.

**Comment by DemonicBroccoli** [comment]
Yeah, that fixed it, same problem as last time, ha.
